-- Supabase用の物件管理テーブル作成SQL

create table if not exists properties (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  rent integer not null,
  area text not null,
  layout text not null,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

create table if not exists admin_users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

alter table properties enable row level security;
-- 既にポリシーが存在する場合に備えて、一度削除してから作成する
-- Supabase の SQL エディタで実行する際、重複エラーを防ぎます
drop policy if exists "Select own properties" on properties;
drop policy if exists "Insert own properties" on properties;
drop policy if exists "Update own properties" on properties;
drop policy if exists "Delete own properties" on properties;

create policy "Select own properties" on properties
  for select
  using (
    user_id = auth.uid() OR exists (
      select 1 from admin_users where email = auth.jwt() ->> 'email'
    )
  );

create policy "Insert own properties" on properties
  for insert
  with check (user_id = auth.uid());

create policy "Update own properties" on properties
  for update
  using (
    user_id = auth.uid() OR exists (
      select 1 from admin_users where email = auth.jwt() ->> 'email'
    )
  )
  with check (
    user_id = auth.uid() OR exists (
      select 1 from admin_users where email = auth.jwt() ->> 'email'
    )
  );

create policy "Delete own properties" on properties
  for delete
  using (
    user_id = auth.uid() OR exists (
      select 1 from admin_users where email = auth.jwt() ->> 'email'
    )
  );
