-- Supabase用の物件管理テーブル作成SQL

create table if not exists properties (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  rent integer not null,
  area text not null,
  layout text not null,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

alter table properties enable row level security;

create policy "Select own properties" on properties
  for select
  using (user_id = auth.uid());

create policy "Insert own properties" on properties
  for insert
  with check (user_id = auth.uid());

create policy "Update own properties" on properties
  for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "Delete own properties" on properties
  for delete
  using (user_id = auth.uid());
